"""The clock mark, as data. Generated by tools/make_logo.py - do not edit.

This is the clock from the project logo, quantised onto a 14x14 grid. Each
string is one row of pixels; each character indexes PALETTE, and "." means
transparent. Two rows become one line of terminal output, drawn with half-block
characters so the pixels stay square.

The full mascot lives in assets/logo.png - it needs fourteen text rows to stay
legible, which is more banner than any command should print.
"""

from __future__ import annotations

PALETTE: dict[str, tuple[int, int, int]] = {
    "o": (0xFE, 0x73, 0x42),
    "d": (0xC4, 0x59, 0x39),
    "k": (0x17, 0x1C, 0x28),
    "b": (0x1B, 0x46, 0x8E),
    "n": (0x1B, 0x3B, 0x71),
    "w": (0xF5, 0xF2, 0xEE),
    "S": (0xCD, 0xD2, 0xDC),
    "s": (0x88, 0x8D, 0x9B),
    "y": (0xFE, 0xB8, 0x33),
}

TRANSPARENT = "."

CLOCK: tuple[str, ...] = (
    "Soooodndoo...y",
    "Soonbbbndok...",
    "oobbnnwwwbbn..",
    "onbnwwwwwwnb..",
    "obnwwwwwwwwbn.",
    "knwwwwwwnwwnb.",
    "knwwwnwnwwwwb.",
    "kbwwwwowwwwwb.",
    "knwwwowwwwwwb.",
    "kbwwwowwwwwnb.",
    "dbbwwwwwwwwbn.",
    "okbnwwwwwwbn..",
    "ookkbbbbbbnn..",
    "..kkkkkkkkkn..",
)

WIDTH = len(CLOCK[0])
HEIGHT = len(CLOCK)
