"""Shell completion, generated from the parser itself.

Hand-written completion scripts rot: someone adds a flag, forgets the script,
and the shell quietly suggests something that no longer exists. Generating them
from the same parser the CLI actually uses makes that impossible.
"""

from __future__ import annotations

import argparse

SHELLS = ("bash", "zsh", "fish")


def _subparsers(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _descriptions(parser: argparse.ArgumentParser) -> dict[str, str]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return {choice.dest: choice.help or "" for choice in action._choices_actions}
    return {}


def _options(parser: argparse.ArgumentParser) -> list[str]:
    flags: set[str] = set()
    for action in parser._actions:
        flags.update(action.option_strings)
    return sorted(flags)


def _global_options(parser: argparse.ArgumentParser) -> list[str]:
    return _options(parser)


def _quote(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "'\\''")


def bash(parser: argparse.ArgumentParser) -> str:
    commands = _subparsers(parser)
    names = " ".join(sorted(commands))
    cases = "\n".join(
        f'        {name}) options="{" ".join(_options(sub))}" ;;'
        for name, sub in sorted(commands.items())
    )
    return f"""\
# claudron completion for bash. Generated by `claudron completion bash`.
_claudron() {{
    local cur command index
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    command=""
    for (( index = 1; index < COMP_CWORD; index++ )); do
        case "${{COMP_WORDS[index]}}" in
            -*) ;;
            *) command="${{COMP_WORDS[index]}}"; break ;;
        esac
    done

    if [[ -z "$command" ]]; then
        COMPREPLY=( $(compgen -W "{names} {" ".join(_global_options(parser))}" -- "$cur") )
        return
    fi

    local options=""
    case "$command" in
{cases}
    esac
    COMPREPLY=( $(compgen -W "$options" -- "$cur") )
}}
complete -F _claudron claudron
"""


def zsh(parser: argparse.ArgumentParser) -> str:
    commands = _subparsers(parser)
    helps = _descriptions(parser)
    described = "\n".join(
        f"        '{name}:{_quote(helps.get(name, ''))}'" for name in sorted(commands)
    )
    cases = "\n".join(
        f"            {name}) opts=({' '.join(_options(sub))}) ;;"
        for name, sub in sorted(commands.items())
    )
    return f"""\
#compdef claudron
# claudron completion for zsh. Generated by `claudron completion zsh`.
_claudron() {{
    local -a commands opts
    commands=(
{described}
    )
    if (( CURRENT == 2 )); then
        _describe -t commands 'claudron command' commands
        return
    fi
    case "${{words[2]}}" in
{cases}
    esac
    compadd -- $opts
}}
_claudron "$@"
"""


def fish(parser: argparse.ArgumentParser) -> str:
    commands = _subparsers(parser)
    helps = _descriptions(parser)
    lines = [
        "# claudron completion for fish. Generated by `claudron completion fish`.",
        "complete -c claudron -f",
    ]
    for name in sorted(commands):
        description = _quote(helps.get(name, ""))
        lines.append(f"complete -c claudron -n __fish_use_subcommand -a {name} -d '{description}'")
    for name, sub in sorted(commands.items()):
        for flag in _options(sub):
            option = f"-l {flag[2:]}" if flag.startswith("--") else f"-s {flag[1:]}"
            lines.append(f'complete -c claudron -n "__fish_seen_subcommand_from {name}" {option}')
    return "\n".join(lines) + "\n"


def script(shell: str, parser: argparse.ArgumentParser) -> str:
    if shell not in SHELLS:
        raise ValueError(f"unsupported shell {shell!r}")
    return {"bash": bash, "zsh": zsh, "fish": fish}[shell](parser)
